config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  resources :posts
  devise_for :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/posts', to: 'posts#index'
  
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  belongs_to :category
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authorize_author, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def post_params
  params.require(:post).permit(:title, :description, :published_at)
end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.author != current_author
      flash[:alert] = "You are not authorized to perform this action"
      redirect_to root_path
    else
      @post.destroy
      flash[:notice] = "Post was successfully deleted"
      redirect_to posts_path
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :description, :published_at, :category_id)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def authorize_author
    unless @post.author_id == current_author.id
      redirect_to root_url, alert: "You are not authorized to perform this action."
    end
  end

  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "shared/navbar" %>
  </head>
  <body>
    <%= yield %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Recognition Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Published at</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.category&.title %></td>
        <td><%= post.published_at %></td>
        <td><%= post.author.email %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>
<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav>
  <div class="logo">
    <%= link_to "Logo", root_path %>
  </div>
  <div class="links">
    <% if current_author %>
      <%= link_to "Sign out", destroy_author_session_path, method: :delete %>
      <%= link_to "Posts", posts_path %>
    <% else %>
      <%= link_to "Sign up", new_author_registration_path %>
      <%= link_to "Sign in", new_author_session_path %>
    <% end %>
  </div>
</nav>